version: '3.8'

services:

  # =============================================
  # DB 컨테이너 (서비스별 분리)
  # =============================================



#  Next에서 인증, spring 토큰 검증이면 필요 없음
#  auth-db:
#    image: mysql:8.0
#    container_name: auth-db
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: auth_db
#    ports:
#      - "3307:3306"
#    volumes:
#      - auth-db-data:/var/lib/mysql
#      - ./auth-service/src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
#    networks:
#      - hana-network

  org-db:
    image: mysql:8.0
    container_name: org-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: org_db
    ports:
      - "3308:3306"
    volumes:
      - org-db-data:/var/lib/mysql
    networks:
      - hana-network

  user-db:
    image: mysql:8.0
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    ports:
      - "3309:3306"
    volumes:
      - user-db-data:/var/lib/mysql
    networks:
      - hana-network

  offering-db:
    image: mysql:8.0
    container_name: offering-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: offering_db
    ports:
      - "3310:3306"
    volumes:
      - offering-db-data:/var/lib/mysql
    networks:
      - hana-network

  activity-db:
    image: mysql:8.0
    container_name: activity-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: activity_db
    ports:
      - "3311:3306"
    volumes:
      - activity-db-data:/var/lib/mysql
    networks:
      - hana-network

  prayer-db:
    image: mysql:8.0
    container_name: prayer-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prayer_db
    ports:
      - "3312:3306"
    volumes:
      - prayer-db-data:/var/lib/mysql
    networks:
      - hana-network

  # =========================
  # 인프라 컨티이너
  # =========================

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - hana-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    networks:
      - hana-network

  # =========================
  # SERVICES
  # =========================

  org-service:
    build: ./org-service
    container_name: org-service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://org-db:3306/org_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - org-db
    networks:
      - hana-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://user-db:3306/user_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - user-db
    networks:
      - hana-network

  offering-service:
    build: ./offering-service
    container_name: offering-service
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://offering-db:3306/offering_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - offering-db
      - kafka
    networks:
      - hana-network

  activity-service:
    build: ./activity-service
    container_name: activity-service
    ports:
      - "8084:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://activity-db:3306/activity_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_PROFILES_ACTIVE: prod
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_REGION: ${AWS_REGION}
    depends_on:
      - activity-db
      - kafka
    networks:
      - hana-network

  prayer-service:
    build: ./prayer-service
    container_name: prayer-service
    ports:
      - "8085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://prayer-db:3306/prayer_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - prayer-db
      - kafka
    networks:
      - hana-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8086:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_COOKIE_NAME: ${JWT_COOKIE_NAME}
    depends_on:
      - kafka
    networks:
      - hana-network

volumes:
  org-db-data:
  user-db-data:
  offering-db-data:
  activity-db-data:
  prayer-db-data:

networks:
  hana-network:
    driver: bridge
