server:
  port: 8080

spring:
  profiles:
    active: local
  application:
    name: org-service

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          time_zone: Asia/Seoul
        order_inserts: true
        order_updates: true
        format_sql: true
        use_sql_comments: true
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/init.sql
      data-locations: classpath:sql/init.sql
