spring:
  profiles:
    active: local
  application:
    name: offering-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://offering-db:3306/offering_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          time_zone: Asia/Seoul
        order_inserts: true
        order_updates: true
        format_sql: true
        use_sql_comments: true
  sql:
    init:
      mode: never

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      properties:
        reconnect:
          backoff:
            ms: 1000
            max:
              ms: 10000
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


feign:
  circuitbreaker:
    enabled: true
