server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: local
  application:
    name: offering-service

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          time_zone: Asia/Seoul
        order_inserts: true
        order_updates: true
        format_sql: true
        use_sql_comments: true
  sql:
    init:
      mode: never
      schema-locations: classpath:sql/init.sql

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      properties:
        reconnect:
          backoff:
            ms: 1000
            max:
              ms: 10000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
feign:
  circuitbreaker:
    enabled: true

security:
  internal:
    hmac-secret: ${INTERNAL_HMAC_SECRET}
    api-key: ${INTERNAL_API_KEY:offering-service-key}
    valid-api-keys: ${INTERNAL_VALID_API_KEYS:user-service-key,activity-service-key,offering-service-key,prayer-service-key,org-service-key}

downstream:
  activity-service: ${ACTIVITY_SERVICE_DOWNSTREAM}
  prayer-service: ${PRAYER_SERVICE_DOWNSTREAM}
  user-service: ${USER_SERVICE_DOWNSTREAM}
  org-service: ${ORG_SERVICE_DOWNSTREAM}