server:
  port: 8082

spring:
  profiles:
    active: local
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://user-db:3306/user_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          time_zone: Asia/Seoul
        order_inserts: true
        order_updates: true
        format_sql: true
        use_sql_comments: true
  sql:
    init:
      mode: never

feign:
  circuitbreaker:
    enabled: true
